"""create initial tables

Revision ID: 0c5ac6c429b0
Revises: 
Create Date: 2026-07-17 23:43:59.482572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5ac6c429b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('marketplace_product_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('seller', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('platform', 'marketplace_product_id', name='uq_products_platform_marketplace_id'),
    sa.UniqueConstraint('url', name='uq_products_url')
    )
    op.create_table('scheduler_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('products_total', sa.Integer(), nullable=True),
    sa.Column('products_scraped', sa.Integer(), nullable=True),
    sa.Column('products_failed', sa.Integer(), nullable=True),
    sa.Column('price_drops_found', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notification_log',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scheduler_runs.run_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('price_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scrape_status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scheduler_runs.run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_subscriptions_user_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('price_history')
    op.drop_table('notification_log')
    op.drop_table('users')
    op.drop_table('scheduler_runs')
    op.drop_table('products')
    # ### end Alembic commands ###
