"""add-products-metadata

Revision ID: e8d4f84f775b
Revises: b3f9d12e4c71
Create Date: 2026-08-02 19:19:25.447834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d4f84f775b'
down_revision: Union[str, Sequence[str], None] = 'b3f9d12e4c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('products', 'mrp', existing_type=sa.NUMERIC(precision=10, scale=2), comment=None, existing_comment='Maximum Retail Price from affiliate API', existing_nullable=True)
    op.alter_column('products', 'special_price', existing_type=sa.NUMERIC(precision=10, scale=2), comment=None, existing_comment='Price after bank/card offers (flipkartSpecialPrice)', existing_nullable=True)
    op.alter_column('products', 'discount_pct', existing_type=sa.NUMERIC(precision=5, scale=2), comment=None, existing_comment='Discount percentage off MRP', existing_nullable=True)
    op.alter_column('products', 'offers', existing_type=postgresql.ARRAY(sa.TEXT()), comment=None, existing_comment='Raw promotional offer strings from affiliate API', existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'offers', existing_type=postgresql.ARRAY(sa.TEXT()), comment='Raw promotional offer strings from affiliate API', existing_nullable=True)
    op.alter_column('products', 'discount_pct', existing_type=sa.NUMERIC(precision=5, scale=2), comment='Discount percentage off MRP', existing_nullable=True)
    op.alter_column('products', 'special_price', existing_type=sa.NUMERIC(precision=10, scale=2), comment='Price after bank/card offers (flipkartSpecialPrice)', existing_nullable=True)
    op.alter_column('products', 'mrp', existing_type=sa.NUMERIC(precision=10, scale=2), comment='Maximum Retail Price from affiliate API', existing_nullable=True)
    op.drop_column('products', 'metadata')
    # ### end Alembic commands ###
